feasible_steps: 
    - WalkDistanceStep
    - BikeDistanceStep
    - TransitReroutedStep
    - BikeSnowDepthStep
    - BikeHighLTSDistStep
    - WalkTimingStep
    - TransitTimingStep
    - BikeTimingStep

probable_steps: 
    - WalkDurationDifferenceStep
    - BikeDurationDifferenceStep
    - TransitDurationDifferenceStep
    - WalkTimingStep
    - BikeTimingStep
    - TransitTimingStep
    - BikeHighLTSDistStep
    - WalkPurposeStep
    - BikePurposeStep
    - TransitPurposeStep
    - TransitTransferCountStep
    - WalkPrecipitationStep
    - BikePrecipitationStep
    - WalkTemperatureStep
    - BikeTemperatureStep

fixed_purposes: ["Work", "Work-related", "Escort", "School", "School-related"]
unlikely_purposes: ["Escort", "Shop"]

force_reinitialize: False
# save_result: False

# assumed to be in data/ directory
community_shape_file_name: "shp_society_thrive_msp2040_com_des"
tbi_file_name: "tbi_full.csv" # recommended to keep it this
weather_file_name: "USW00014922.csv"

# just put whatever path you have in your keyring 
drive_data_dir: 'D:/University of Kentucky/VMT Reduction Mode Shift - General'

keep_columns:
    - mode
    - o_purpose_category
    - d_purpose_category
    - gender
    - age
    - student_status
    - job_type
    - num_kids
    - travel_date
    - home_lon
    - home_lat
    - income_broad
    - duration
    - distance
    - person_id
    - trip_id
    - wave
    - depart_time
    - arrive_time
    - travel_dow
    - vmt
    - vehicle_trips



cold_start_threshold: 15