feasible_steps: 
    - WalkDistanceStep
    - BikeDistanceStep
    - TransitReroutedStep
    - BikeSnowDepthStep
    - BikeHighLTSDistStep
    - WalkTimingStep
    - TransitTimingStep
    - BikeTimingStep

probable_steps: 
    - WalkDurationDifferenceStep
    - BikeDurationDifferenceStep
    - TransitDurationDifferenceStep
    # - WalkTimingStep
    # - BikeTimingStep
    # - TransitTimingStep
    - BikeHighLTSDistStep
    - WalkPurposeStep
    - BikePurposeStep
    - TransitPurposeStep
    - TransitTransferCountStep
    - WalkPrecipitationStep
    - BikePrecipitationStep
    - WalkTemperatureStep
    - BikeTemperatureStep

fixed_purposes: ["Work", "Work-related", "Escort", "School", "School-related"]
unlikely_purposes: ["Escort", "Shop"]

build: False  # whether we are currently building to docker/streamlit; disables initialization/keyring
force_reinitialize: False
# save_result: False

# assumed to be in data/ directory
community_shape_file_name: "shp_bdry_census2020counties_ctus/Census2020CTUs.shp"
tbi_file_name: "tbi_full.csv"  # recommended to keep it this; must be parquet or csv
weather_file_name: "USW00014922.csv"
taz_terminal_time_file_name: "taz_terminal_times/TAZ3030_Terminal_times.shp"

keep_columns:
    - mode
    - o_purpose_category
    - d_purpose_category
    - gender
    - age
    - student_status
    - job_type
    - num_kids
    - travel_date
    - home_lon
    - home_lat
    - income_detailed
    - duration
    - distance
    - person_id
    - trip_id
    - wave
    - depart_time
    - arrive_time
    - travel_dow
    - vmt
    - vehicle_trips
    - o_lat
    - o_lon
    - d_lat
    - d_lon
    - trip_weight

scenario_columns:
    bike:
        # the format for scenarios is [title, new_column, replaced_column]
        - [default, None, None]
    transit:
        - [default, None, None]
    walk:
        - [default, None, None]
    car:
        - [default, None, None]

cold_start_threshold: 15