# Calibration

```{python}
#| include: false
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from os.path import join, abspath, dirname
import sys
import keyring
import numpy as np
import zipfile

# This is used to avoid hard-coding directories. 
# To set the directory, use the command prompt or a notebook you don't check in.  run:
# import keyring
# keyring.set_password("msp", "vmt_reduction_dir", <directory>)

# get base path for data
data_dir = keyring.get_password("msp", "vmt_reduction_dir")

# This cell sets the file names for the different modes/scenarios - it can be updated to use
# newer versions of the data
CAR_BASELINE = "car_congestion_1d39c/car_congestion.parquet"
CAR_SCENARIO = "car_scenario_f2802.parquet"
BIKE_BASELINE = "bike-lts-37721.parquet"
BIKE_SCENARIO_LTS1 = "bike-all-lts1-37721.parquet"
EBIKE_SCENARIO = "bike-ebike-8a1a0-1.parquet"
WALK_BASELINE = "walk-trips-1d39c.parquet"
WALK_SCENARIO = "walk-scenario-a37e1.parquet"
TRANSIT_BASELINE = "transit-trips-45d51.parquet"
TRANSIT_BASELINE = "transit-scenario-0277d.parquet"

tbi = pd.read_csv(data_dir + "/data_processed/tbi_cleaned.csv", low_memory=False)
```

To ensure our routing is reflective of reality, we check the routed travel times for trips of each mode against the observed travel time of trips by that mode in the TBI.

For autos and bikes, we include terminal times in the analysis. While the actual terminal time calculation in the analysis is more involved,we assume a flat 3 minute terminal time per car trip in this section (i.e. 90 seconds per trip end). With the terminal time included, the median routed auto trip is 2% longer than the corresponding observed trip (@fig-auto-calibration).

```{python}
#| label: fig-auto-calibration
#| fig-cap: Ratio of routed to observed travel times by auto, including 3 minutes terminal time
#| fig-alt: Histogram showing that the median routed auto trip is 2% longer than the corresponding observed trip. There is significant spread between a ratio of zero and two, likely because of day-to-day variations, individual non-optimal route choices, and rounding of arrival/departure times by respondents.
car_baseline = gpd.read_parquet(join(data_dir, "Data_Processed", "geodata", CAR_BASELINE))
car_baseline = car_baseline.merge(tbi, how="left", on="trip_id", validate="1:1")
observed_car_baseline = car_baseline[car_baseline["mode"] == "Car"].copy()

observed_car_baseline["ratio_routed_to_observed"] = (
    (observed_car_baseline.duration_seconds / 60 + 3) /
    observed_car_baseline.duration
)

plt.hist(np.minimum(observed_car_baseline.ratio_routed_to_observed, 5), bins=50)
plt.xlabel(f"Ratio of routed to observed time (topcoded at 5)\nmedian: {observed_car_baseline.ratio_routed_to_observed.median():.2f}");
```

For bikes, a flat two minutes of terminal time is included. The median bike trip is 24% longer than observed (@fig-bike-calibration). However, this is somewhat expected, as the people who are biking now are more confident and faster cyclists, more willing to take more direct but stressful routes, than the cyclist we're modeling.

```{python}
#| label: fig-bike-calibration
#| fig-cap: Ratio of routed to observed travel times by bike, including 2 minutes terminal time
#| fig-alt: Histogram showing that the median routed bike trip is 24% longer than the corresponding observed trip. There is even more spread than there is with autos, likely because there is significant variability in speed and route choice behavior for observed cyclists.
bike_baseline = gpd.read_parquet(join(data_dir, "Data_Processed", "geodata", BIKE_BASELINE))
bike_baseline = bike_baseline.merge(tbi, how="left", on="trip_id", validate="1:1")
observed_bike_baseline = bike_baseline[bike_baseline["mode"] == "Bike/Scooter"].copy()

observed_bike_baseline["ratio_routed_to_observed"] = (
    (observed_bike_baseline.duration_seconds / 60 + 2) /
    observed_bike_baseline.duration
)

plt.hist(np.minimum(observed_bike_baseline.ratio_routed_to_observed, 5), bins=50)
plt.xlabel(f"Ratio of routed to observed time (topcoded at 5)\nmedian: {observed_bike_baseline.ratio_routed_to_observed.median():.2f}");
```

For walking, we do not include any terminal time, as you do not need to access a vehicle, etc. (and presumably tying your shoes is a constant across all modes). The median routed walk trip is 23% faster than the corresponding observed trip (@fig-walk-calibration). This would seem to suggest that our assumed walking speeds or routes may be optimistic, but it may also be because many of the walk trips in the TBI are at least partly for leisure/exercise/recreation and may not take the same path or travel at the same speed they would if they were transportation trips.

```{python}
#| label: fig-walk-calibration
#| fig-cap: Ratio of routed to observed travel times by walking, with no terminal time
#| fig-alt: Histogram showing that the median routed walk trip is 24% longer than the corresponding observed trip. There is even more spread than there is with autos, likely because there is significant variability in speed and route choice behavior for observed cyclists.
walk_baseline = gpd.read_parquet(join(data_dir, "Data_Processed", "geodata", WALK_BASELINE))
walk_baseline = walk_baseline.merge(tbi, how="left", on="trip_id", validate="1:1")
observed_walk_baseline = walk_baseline[walk_baseline["mode"] == "Walk"].copy()

observed_walk_baseline["ratio_routed_to_observed"] = (
    (observed_walk_baseline.duration_seconds / 60) /
    observed_walk_baseline.duration
)

plt.hist(np.minimum(observed_walk_baseline.ratio_routed_to_observed, 5), bins=50)
plt.xlabel(f"Ratio of routed to observed time (topcoded at 5)\nmedian: {observed_walk_baseline.ratio_routed_to_observed.median():.2f}");
```

The transit trips are a bit different, due to the time dependence. We calculate the routed travel time as the routed arrival time minus the earlier of the observed or routed departure time in the case of forward-routed trips (the routed departure time may be slightly earlier since we use soft constraints on departure/arrival times). For reverse-routed trips, we calculate the later of the observed or routed arrival time minus the routed departure time. We find the median routed transit trip is 9% longer than observed (@fig-transit). However, there are a large number of trips topcoded at a ratio of over 5:1. These may represent trips on other transit systems, and are worthy of further investigation. 7% of observed transit trips, furthermore, failed to route at all.

```{python}
#| fig-cap: Ratio of routed to observed time for transit trips
#| label: fig-transit
#| fig-alt: Histogram peaking around 1, slightly right-skewed, with many values topcoded at five

transit_baseline_legs = gpd.read_parquet(join(data_dir, "Data_Processed", "geodata", TRANSIT_BASELINE))

# calculate the arrival and departure times we will use for the comparison (logic described in text)
# convert dates and times, accounting for the "representative week"
tbi["travel_date"] = pd.to_datetime(tbi.travel_date)

tbi.loc[tbi.travel_date.dt.day_name() == "Sunday", "representative_travel_date"] = "2019-10-20"
tbi.loc[tbi.travel_date.dt.day_name() == "Monday", "representative_travel_date"] = "2019-10-21"
tbi.loc[tbi.travel_date.dt.day_name() == "Tuesday", "representative_travel_date"] = "2019-10-22"
tbi.loc[tbi.travel_date.dt.day_name() == "Wednesday", "representative_travel_date"] = "2019-10-23"
tbi.loc[tbi.travel_date.dt.day_name() == "Thursday", "representative_travel_date"] = "2019-10-24"
tbi.loc[tbi.travel_date.dt.day_name() == "Friday", "representative_travel_date"] = "2019-10-25"
tbi.loc[tbi.travel_date.dt.day_name() == "Saturday", "representative_travel_date"] = "2019-10-26"

# this can't possibly be the best way to do this can it?
tbi["representative_depart_time"] = pd.to_datetime(tbi.representative_travel_date + " " + tbi.depart_time)
tbi["representative_arrive_time"] = pd.to_datetime(tbi.representative_travel_date + " " + tbi.arrive_time)

# This is what is done in route.jl. TODO need to check if travel_date is always the day the trip started, or if it is 3am-3am or something.
tbi.loc[tbi.representative_arrive_time < tbi.representative_depart_time, "representative_arrive_time"] += pd.DateOffset(1)

# combine legs
transit_baseline = (
    transit_baseline_legs
        .sort_values(["trip_id", "leg_index"]) # should be no-op, very fast
        .groupby("trip_id").aggregate({
            "start_time": "first",
            "end_time": "last",
            "reverse": "first"
        })
)

transit_baseline = transit_baseline.merge(tbi, how="right", on="trip_id", validate="1:1")
observed_transit_baseline = transit_baseline[transit_baseline["mode"] == "Transit"].copy()

observed_transit_baseline.loc[observed_transit_baseline.reverse == 0, "canonical_departure"] = np.minimum(
        observed_transit_baseline.representative_depart_time,
        observed_transit_baseline.start_time
    )

observed_transit_baseline.loc[observed_transit_baseline.reverse == 1, "canonical_departure"] = observed_transit_baseline.start_time

observed_transit_baseline.loc[observed_transit_baseline.reverse == 0, "canonical_arrival"] = observed_transit_baseline.end_time

observed_transit_baseline.loc[observed_transit_baseline.reverse == 1, "canonical_arrival"] = np.maximum(
        observed_transit_baseline.representative_arrive_time,
        observed_transit_baseline.end_time
    )

observed_transit_baseline["routed_time"] = (observed_transit_baseline.canonical_arrival - observed_transit_baseline.canonical_departure).dt.seconds / 60
observed_transit_baseline["ratio_routed_to_observed"] = observed_transit_baseline.routed_time / observed_transit_baseline.duration

success = ~observed_transit_baseline.reverse.isnull()

plt.hist(np.minimum(observed_transit_baseline.loc[success, "ratio_routed_to_observed"], 5), bins=50)
plt.xlabel(f"Ratio of routed to observed time (topcoded at 5)\nmedian: {observed_transit_baseline.ratio_routed_to_observed.median():.2f}\n{(1 - success.mean()) * 100:.0f}% of trips failed to route");
```