# Transit Baseline QC

```{python}
#| include: false
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from os.path import join, abspath, dirname
import sys
import keyring
import numpy as np
import zipfile
import yaml

# This is used to avoid hard-coding directories. 
# To set the directory, use the command prompt or a notebook you don't check in.  run:
# import keyring
# keyring.set_password("msp", "vmt_reduction_dir", <directory>)

# get base path for data
data_dir = keyring.get_password("msp", "vmt_reduction_dir")

with open("input_files.yml") as fls:
    input_files = yaml.safe_load(fls)

tbi = pd.read_csv(data_dir + "/data_processed/tbi_cleaned.csv", low_memory=False)
```

Calibration of the transit trips is a bit different, due to the time dependence. We calculate the routed travel time as the routed arrival time minus the earlier of the observed or routed departure time in the case of forward-routed trips (the routed departure time may be slightly earlier since we use soft constraints on departure/arrival times). For reverse-routed trips, we calculate the later of the observed or routed arrival time minus the routed departure time. We find the median routed transit trip is 9% longer than observed (@fig-transit). However, there are a large number of trips topcoded at a ratio of over 5:1. These may represent trips on other transit systems, and are worthy of further investigation. 7% of observed transit trips, furthermore, failed to route at all.

```{python}
#| fig-cap: Ratio of routed to observed time for transit trips
#| label: fig-transit
#| fig-alt: Histogram peaking around 1, slightly right-skewed, with many values topcoded at five

transit_baseline_legs = gpd.read_parquet(join(data_dir, "Data_Processed", "geodata", input_files["transit"]["baseline"]))

# calculate the arrival and departure times we will use for the comparison (logic described in text)
# convert dates and times, accounting for the "representative week"
tbi["travel_date"] = pd.to_datetime(tbi.travel_date)

tbi.loc[tbi.travel_date.dt.day_name() == "Sunday", "representative_travel_date"] = "2019-10-20"
tbi.loc[tbi.travel_date.dt.day_name() == "Monday", "representative_travel_date"] = "2019-10-21"
tbi.loc[tbi.travel_date.dt.day_name() == "Tuesday", "representative_travel_date"] = "2019-10-22"
tbi.loc[tbi.travel_date.dt.day_name() == "Wednesday", "representative_travel_date"] = "2019-10-23"
tbi.loc[tbi.travel_date.dt.day_name() == "Thursday", "representative_travel_date"] = "2019-10-24"
tbi.loc[tbi.travel_date.dt.day_name() == "Friday", "representative_travel_date"] = "2019-10-25"
tbi.loc[tbi.travel_date.dt.day_name() == "Saturday", "representative_travel_date"] = "2019-10-26"

# this can't possibly be the best way to do this can it?
tbi["representative_depart_time"] = pd.to_datetime(tbi.representative_travel_date + " " + tbi.depart_time)
tbi["representative_arrive_time"] = pd.to_datetime(tbi.representative_travel_date + " " + tbi.arrive_time)

# This is what is done in route.jl. TODO need to check if travel_date is always the day the trip started, or if it is 3am-3am or something.
tbi.loc[tbi.representative_arrive_time < tbi.representative_depart_time, "representative_arrive_time"] += pd.DateOffset(1)

# combine legs
transit_baseline = (
    transit_baseline_legs
        .sort_values(["trip_id", "leg_index"]) # should be no-op, very fast
        .groupby("trip_id").aggregate({
            "start_time": "first",
            "end_time": "last",
            "reverse": "first"
        })
)

transit_baseline = transit_baseline.merge(tbi, how="right", on="trip_id", validate="1:1")
observed_transit_baseline = transit_baseline[transit_baseline["mode"] == "Transit"].copy()

observed_transit_baseline.loc[observed_transit_baseline.reverse == 0, "canonical_departure"] = np.minimum(
        observed_transit_baseline.representative_depart_time,
        observed_transit_baseline.start_time
    )

observed_transit_baseline.loc[observed_transit_baseline.reverse == 1, "canonical_departure"] = observed_transit_baseline.start_time

observed_transit_baseline.loc[observed_transit_baseline.reverse == 0, "canonical_arrival"] = observed_transit_baseline.end_time

observed_transit_baseline.loc[observed_transit_baseline.reverse == 1, "canonical_arrival"] = np.maximum(
        observed_transit_baseline.representative_arrive_time,
        observed_transit_baseline.end_time
    )

observed_transit_baseline["routed_time"] = (observed_transit_baseline.canonical_arrival - observed_transit_baseline.canonical_departure).dt.seconds / 60
observed_transit_baseline["ratio_routed_to_observed"] = observed_transit_baseline.routed_time / observed_transit_baseline.duration

success = ~observed_transit_baseline.reverse.isnull()

plt.hist(np.minimum(observed_transit_baseline.loc[success, "ratio_routed_to_observed"], 5), bins=50)
plt.xlabel(f"Ratio of routed to observed time (topcoded at 5)\nmedian: {observed_transit_baseline.ratio_routed_to_observed.median():.2f}\n{(1 - success.mean()) * 100:.0f}% of trips failed to route");
```

## Trips with a high routed to observed travel time

Many trips have a routed to observed travel time ratio of over 5. In this section I explore some of these trips to try to understand why the routed path is so much longer. We will start by plotting the routed and observed travel times.

```{python}
high_ratio = observed_transit_baseline[observed_transit_baseline.ratio_routed_to_observed >= 5].copy()
plt.scatter(high_ratio.duration, high_ratio.routed_time, s=0.5)
plt.xlabel("Observed travel time (minutes)")
plt.ylabel("Routed travel time (minutes)")
```

The next logical question is whether this is driven by initial waiting time. Here, I compare the time in transit (in-vehicle + waiting at transfers) to the reported time.

```{python}
high_ratio["routed_transit_time"] = (high_ratio.end_time - high_ratio.start_time).dt.seconds / 60
plt.axline((0, 0), (1, 1), color="red")
plt.scatter(high_ratio.duration, high_ratio.routed_transit_time, s=0.5)
plt.xlabel("Observed travel time (minutes)")
plt.ylabel("Routed travel time (minutes, excluding initial wait)")
```

That doesn't look very different. The next step is to see where these trips are taking place. Let's look at the counties where they are starting and ending.

```{python}
high_ratio.groupby(["o_county", "d_county"]).size().unstack().fillna(0).astype("int64")
```

Most of these are trips that took place within Hennepin County.

Next, we can plot the locations. This isn't really a map, but it should give some idea of where these trips are geographically.

```{python}
plt.scatter(high_ratio.o_lon, high_ratio.o_lat)
```

That is pretty much the same distribution as all the other transit trips. Let's look at some of the actual trips.

```{python}
transit_baseline_legs[transit_baseline_legs.trip_id.isin(high_ratio.trip_id)].plot()
```

That doesn't seem to clear it up much either. Are they happening late at night?

```{python}
plt.hist(high_ratio.start_time.dt.hour)
plt.xlabel("Departure, hour of day")
```


```{python}
# dump to GIS
transit_baseline_legs[transit_baseline_legs.trip_id.isin(high_ratio.trip_id)].to_file(join(data_dir, "Data_Processed", "geodata", "transit_strange_trips_test.gpkg"))
```

## Spot check results

```{python}
orig_trips19 = pd.read_csv(join(data_dir, "Data", "TBI Wave 1 Dataset 20200630 - Decoded", "trip.csv"))
orig_trips22 = pd.read_csv(join(data_dir, "Data", "Wave 2 Data Deliverable", "trip.csv"))
```

### Trip [1950639104008]

This trip goes from the General Mills campus west of Minneapolis to Elk River, an extreme northern suburb, at 6:00 AM, and arrives at 6:20 AM. The routed trip waits until the afternoon, and takes the Northstar commuter rail, which takes much longer. I can't find any transit line that would make that possible, and it's not on Google Maps, so I suspect this was a driving trip that got misclassified.

### Trip [2200267201003, 2200267201004, 2200267201005]

This one is strange. Trip 2200267201005 has mode type walk, but detailed mode type local bus. The route that we find involves an overnight transfer to the 25, which does not run late enough to serve this trip. My best guess as to what actually happened is that they took the 10 and then walked 2.5 km to the destination, but that would have just barely exceeded our egress distance limit, I think, especially if the router moved them off the most direct but scary-to-walk-on street.

## Trip [1940073802029]

This trip allegedly took only three minutes to travel 1.5 km as the crow flies (longer as the horse flies) by light rail. It is a trip from a location adjacent to the 38th Street light rail station, and traveled to a location 1.1 km away from the 46th St station. I suspect they did not report the egress time; the routed travel time from the origin to the 46th St station is in fact about 3 minutes, followed by a 1.1 km, 13 minute walk.

## Trip [1975579403001]

This trip departed at 5:50 and arrived at 6:20, but has a recorded duration of only 11 minutes. This is present in the raw TBI data, it's not a result of the UKY/UNC cleaning process. I'm not sure how that was calculated. The routed trip is 56 minutes, and claims it used an express bus. I suspect they used the 535, which departs 46th St at 5:32 and 6:02. This is an arrive-by trip, and the 6:02 does not get to the destination quite quick enough to arrive by 6:20. The router does find the 5:32 trip, but it is not the latest-departure-given-earliest-arrival trip.

## Trip [1952944101002]

This is a trip from the airport to downtown that allegedly took six minutes. This seems clearly to be bad data.

### Trip [2200006401033, 2200006401025, 2200006401038]

This trip starts at Maplewood Mall at 12:34 AM. None of the vehicles in our GTFS serve Maplewood Mall that late, so the router waits until the next morning.

### Trip [1926461102014]

This is a trip from St Louis Park to Tonka Bay that took 32 minutes. That seems unlikely to be possible on transit, so probably a driving trip misclassified as transit.

