---
title: Transit Scenario QC
author: Matt Bhagat-Conway
bibliography: bibliography.bib
---

This checks a couple of assumptions about the transit scenario results, notably:

1. Every trip in the baseline should be possible in the scenario as well.
2. Unlike the bike and walk scenarios, the transit scenario should be strictly better---all the existing trips remain in the network, and have just been duplicated. Travel time may get longer on some trips, but arrival time should always be the same or earlier.
3. Due to the [structure of the range-RAPTOR algorithm](https://projects.indicatrix.org/range-raptor-transfer-compression/), trips that have the same arrival time should leave at the same time or later in the scenario, even if the scenario adds an earlier-departure option. The optimization gives latest departure given earliest arrival trips.
4. Roughly half the trips should have earlier arrival times in the one-ride case, because they fall in the half of the headway that was before. It may be less in the three-ride case, because you might get an earlier trip to a transfer point that gets you on the same vehicle you would have gotten on otherwise.


```{julia}
using Parquet, DataFrames, DataFramesMeta, CSV, Dates, StatsBase

DATA_DIR = readchomp(`keyring get vmt_reduction_dir`)
```

## Load data

We load the transit baseline, transit scenario, and the one-transfer versions of each.

```{julia}
baseline = read_parquet(joinpath(DATA_DIR, "geodata", "transit-trips-93d71.parquet")) |> DataFrame;
scenario = read_parquet(joinpath(DATA_DIR, "geodata", "transit-scenario-93d71.parquet")) |> DataFrame;
baseline_oneseat = read_parquet(joinpath(DATA_DIR, "geodata", "transit-notransfer-93d71.parquet")) |> DataFrame;
scenario_oneseat = read_parquet(joinpath(DATA_DIR, "geodata", "transit-notransfer-scenario-93d71.parquet")) |> DataFrame;
```

```{julia}
tbi = CSV.read(joinpath(DATA_DIR, "tbi_cleaned.csv"), DataFrame);
```

```{julia}
REPRESENTATIVE_WEEK::Date = Date(2019, 10, 19)
select_representative_date(date) = Dates.tonext(x -> dayofweek(x) == dayofweek(date), REPRESENTATIVE_WEEK)
tbi.arrive_datetime = DateTime.(select_representative_date.(tbi.travel_date), tbi.arrive_time)
tbi.depart_datetime = DateTime.(select_representative_date.(tbi.travel_date), tbi.depart_time);
```

## Check assumptions

### Assumption 1: all trips in the baseline are in the scenario

They may not have the same number of trips (the scenario may have made some trips possible that weren't before, e.g. by catching a new bus that allows you catch the last run of the bus carrying you home), but every baseline trip should be in the scenario.
```{julia}
@assert all(baseline.trip_id .∈ Ref(Set(scenario.trip_id)))
@assert all(baseline_oneseat.trip_id .∈ Ref(Set(scenario_oneseat.trip_id)))
```

### Assumptions 2 and 3: all trips got better

For depart-at (forward search) trips, all trips should arrive at the same time or earlier. The one exception is trips that violate the depart-at constraint; violations of up to five minues are allowed if they improve the arrival/departure time by at least 15 minutes. Some trips where violations improved the travel time sufficiently in the baseline may no longer in the scenario, because of a new trip that does meet the constraint, or violates it less.

If both baseline and scenario trips arrive at the same time, they should leave at the same time or later. The exception to this is when _both_ trips involve an initial wait longer than two hours, which is the burn-in period we are using. In a forward search, Range-RAPTOR only guarantees that it will find the latest departure given earliest arrival when the second-latest departure is within the burn-in period (see the [edge effects section of this preprint](https://projects.indicatrix.org/range-raptor-transfer-compression/)). Otherwise, it only guarantees earliest arrival, and the departure time is undefined behavior (it will have to do with things like the order of trips in the GTFS, etc.)

It seems there are a few additional trips where the departure moves a little earlier (less than one minute), I suspect this is an inconsistency in OSRM.

For arrive-by (reverse search) trips, all trips should leave at the same time or later, with a similar exception for trips violating the constraint. If they leave at the same time, they should arrive at the same time or earlier. Reverse searches with Range-RAPTOR do not use a burn in period, and thus guarantee the earliest arrival given latest departure in all cases.

```{julia}
summarize_trips(trips) = @chain trips begin
    groupby(:trip_id)
    @combine(:start_time = unix2datetime(minimum(:start_time) // 1000), :end_time = unix2datetime(maximum(:end_time // 1000)), :reverse=first(:reverse))
end

baseline_trips = summarize_trips(baseline)
scenario_trips = summarize_trips(scenario)
baseline_oneseat_trips = summarize_trips(baseline_oneseat)
scenario_oneseat_trips = summarize_trips(scenario_oneseat)

joined_trips = @chain begin 
    leftjoin(baseline_trips, scenario_trips, on=:trip_id, renamecols=:_baseline=>:_scenario) 
    leftjoin(tbi, on=:trip_id)
end
joined_oneseat_trips = @chain begin
    leftjoin(baseline_oneseat_trips, scenario_oneseat_trips, on=:trip_id, renamecols=:_baseline=>:_scenario)
    leftjoin(tbi, on=:trip_id)
end;
```

```{julia}
@assert all(joined_trips.reverse_baseline .== joined_trips.reverse_scenario)
@assert all(joined_oneseat_trips.reverse_baseline .== joined_oneseat_trips.reverse_scenario)

for trips in (joined_trips, joined_oneseat_trips)
    # depart-at trips arrival time
    @assert all(
        # Arrives at the same time or earlier
        (trips.end_time_scenario .≤ trips.end_time_baseline) .||
        (
            # or previously violated constraint
            (trips.start_time_baseline .< trips.depart_datetime) .&&
            # and now no longer does, or does less
            (trips.start_time_scenario .≥ trips.start_time_baseline)) .|| 
        # or is not a depart at trip
        (trips.reverse_baseline .== 1)
    )

    # depart-at trips departure time
    @assert all(
        # they have different end times
        (trips.end_time_scenario .≠ trips.end_time_baseline) .||
        # or the departure is the same or later (with some tolerance for what I think is an OSRM issue - investigate further)
        (trips.start_time_scenario .- trips.start_time_baseline .> -Second(60)) .||
        # or both the original departure time and the new one are more than 2 hours after the requested time,
        # in which case the burn in period cannot guarantee a latest departure, only an earliest arrival
        # (see the paragraph about edge effects in https://projects.indicatrix.org/range-raptor-transfer-compression/)
        ((trips.start_time_scenario .- trips.depart_datetime .≥ Hour(2)) .&& trips.start_time_baseline .- trips.depart_datetime .≥ Hour(2)) .||
        # or is not a depart at trip
        (trips.reverse_baseline .== 1)
    )

    # arrive-by trips departure time
    @assert all(
        # leaves at the same time or later (again, with allowance for OSRM issue)
        (trips.start_time_scenario .- trips.start_time_baseline .> -Second(60)) .||
        (
            # or previously violated constraint
            (trips.end_time_baseline .> trips.arrive_datetime) .&&
            # and now does not, or violates less
            (trips.end_time_scenario .< trips.end_time_baseline)
        ) .||
        # or is not an arrive-by trip
        (trips.reverse_baseline .== 0)
    )

    # arrive-by trips arrival time
    @assert all(
        # they do not depart at the same time
        # TODO ideally we'd have a tolerance for OSRM here, but it's hard to differentiate
        # between an improved trip that got 30 seconds faster and an OSRM
        # issue that changed the time by 30 seconds
        (trips.start_time_scenario .≠ trips.start_time_baseline) .||
        # or they arrive at the same time or earlier
        (trips.end_time_scenario .≤ trips.end_time_baseline) .||
        # or is not an arrive-by trip
        (trips.reverse_baseline .== 0)
    )
end
```

### Assumption 4: Roughly half of trips in the one-ride scenario got better

```{julia}
@chain joined_oneseat_trips begin
    @subset (:reverse_baseline .== 0)
    @with mean(:end_time_scenario .< :end_time_baseline)
end
```

34% is somewhat lower than the theoretically expected 50%. I can think of two explanations for this. One is that span-of-service is not expanded in the scenario, so trips where the requested departure time is before service begins will still get on the same vehicle. But probably the main explanation is a flaw in the reasoning that led to the assumption of 50% of trips improving. The assumption that makes is that riders _of a particular vehicle_ depart their origin uniformly randomly between when the previous vehicle on that route ran and when this vehicle runs (assuming zero travel time from origin to the board stop, but the argument generalizes easily). Under this assumption, doubling frequency improves travel time for half the riders---the half that arrived in the first half of the interval between vehicles. However, this assumption breaks down when there are multiple options for travel from the origin to the destination. In this case, the longer the time before the next departure on the given route, the more likely there is to be an alternate path that arrives at the destination sooner. Therefore, less than half of the people on a particular vehicle will have arrived more than half the headway before the departure; the closer the desired departure is to the actual departure, the more likely a rider is to choose that vehicle. See also @stewart_half_2022 for a more extensive discussion of this topic.